### ISSUE TITLE
Integrating Existing Simple Examples 

### ISSUE THREAD

**Issue by bbiiggppiigg** [dyninst/examples#2]
A link to a simpler but outdated tutorial is here.
http://pages.cs.wisc.edu/~roundy/coverage/
It might be useful to include this example/tutorial into this project.

**Comment by hainest** [comment]
@bbiiggppiigg We're not sure what the format will be. You can submit a PR in this repo once you get them working, and then we'll figure out formatting.

**Comment by bbiiggppiigg** [comment]
@hainest The latest commit will compile the examples with CMake

**Comment by MandrakeCQC** [comment]
I noticed that ParseAPI, PatchAPI, SymtabAPI also come with some examples in their documentation, would it make sense for us to move them too? If so, I can get those for ParseAPI and PatchAPI done.

**Comment by hainest** [comment]
@MandrakeCQC Yes, we'll want to move them into this repo. Eventually, we'll want some way to synchronize that code with the documentation text so that the documentation examples can be automatically tested on every update (see #711). However, that is for later. The first step is to extract them out of the docs and into compilable code. Feel free to submit that as a separate PR.

**Comment by hainest** [comment]
Closed by #3
