### ISSUE TITLE
Examples does not configure correctly when a dyninst is specified on the command line.

### ISSUE THREAD

**Issue by bigtrak** [dyninst/examples#33]
If a Dyninst_DIR is specified to cmake, that should be the only dyninst used 
by the examples build.   If that dyninst is missing, or otherwise not found, cmake
should abort.

Instead what happens is  the examples cmake config will silently find a "random" 
version of dyninst installed elsewhere on the system.

The current failure mode is that you will receive a "random" version of dyninst,
instead of the dyninst the examples needs to be built against.

**Comment by hainest** [comment]
>If a Dyninst_DIR is specified to cmake, that should be the only dyninst used
by the examples build. If that dyninst is missing, or otherwise not found, cmake
should abort.

This isn't possible to do in the general case because of the way CMake does package resolution through `find_package` (see https://cmake.org/cmake/help/v3.13/command/find_package.html#search-procedure). You can interrupt some of the stages, but you can't completely override them until 3.24.

>Instead what happens is the examples cmake config will silently find a "random"
version of dyninst installed elsewhere on the system.

It's not random. It's the first package that satisfies the `find_package` constraints. This may or may not be the first package that it _finds_ during lookup. It will skip non-conforming packages.
